// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: utils.proto

package utils

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PacketClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd    int32  `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Msisdn uint64 `protobuf:"varint,2,opt,name=Msisdn,proto3" json:"Msisdn,omitempty"`
	Imsi   uint64 `protobuf:"varint,3,opt,name=Imsi,proto3" json:"Imsi,omitempty"`
	Cmnd   string `protobuf:"bytes,4,opt,name=Cmnd,proto3" json:"Cmnd,omitempty"`
	Name   string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Dob    string `protobuf:"bytes,6,opt,name=Dob,proto3" json:"Dob,omitempty"`
}

func (x *PacketClient) Reset() {
	*x = PacketClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_utils_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketClient) ProtoMessage() {}

func (x *PacketClient) ProtoReflect() protoreflect.Message {
	mi := &file_utils_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketClient.ProtoReflect.Descriptor instead.
func (*PacketClient) Descriptor() ([]byte, []int) {
	return file_utils_proto_rawDescGZIP(), []int{0}
}

func (x *PacketClient) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *PacketClient) GetMsisdn() uint64 {
	if x != nil {
		return x.Msisdn
	}
	return 0
}

func (x *PacketClient) GetImsi() uint64 {
	if x != nil {
		return x.Imsi
	}
	return 0
}

func (x *PacketClient) GetCmnd() string {
	if x != nil {
		return x.Cmnd
	}
	return ""
}

func (x *PacketClient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PacketClient) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

type PacketServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd     int32  `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Rescode int32  `protobuf:"varint,2,opt,name=Rescode,proto3" json:"Rescode,omitempty"`
	Reason  string `protobuf:"bytes,3,opt,name=Reason,proto3" json:"Reason,omitempty"`
}

func (x *PacketServer) Reset() {
	*x = PacketServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_utils_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketServer) ProtoMessage() {}

func (x *PacketServer) ProtoReflect() protoreflect.Message {
	mi := &file_utils_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketServer.ProtoReflect.Descriptor instead.
func (*PacketServer) Descriptor() ([]byte, []int) {
	return file_utils_proto_rawDescGZIP(), []int{1}
}

func (x *PacketServer) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *PacketServer) GetRescode() int32 {
	if x != nil {
		return x.Rescode
	}
	return 0
}

func (x *PacketServer) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_utils_proto protoreflect.FileDescriptor

var file_utils_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75,
	0x74, 0x69, 0x6c, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x0c, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x73, 0x69, 0x73, 0x64,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x4d, 0x73, 0x69, 0x73, 0x64, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x49, 0x6d, 0x73, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x49,
	0x6d, 0x73, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6d, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x43, 0x6d, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x44,
	0x6f, 0x62, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x44, 0x6f, 0x62, 0x22, 0x52, 0x0a,
	0x0c, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x52, 0x65, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_utils_proto_rawDescOnce sync.Once
	file_utils_proto_rawDescData = file_utils_proto_rawDesc
)

func file_utils_proto_rawDescGZIP() []byte {
	file_utils_proto_rawDescOnce.Do(func() {
		file_utils_proto_rawDescData = protoimpl.X.CompressGZIP(file_utils_proto_rawDescData)
	})
	return file_utils_proto_rawDescData
}

var file_utils_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_utils_proto_goTypes = []interface{}{
	(*PacketClient)(nil), // 0: utils.PacketClient
	(*PacketServer)(nil), // 1: utils.PacketServer
}
var file_utils_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_utils_proto_init() }
func file_utils_proto_init() {
	if File_utils_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_utils_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_utils_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_utils_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_utils_proto_goTypes,
		DependencyIndexes: file_utils_proto_depIdxs,
		MessageInfos:      file_utils_proto_msgTypes,
	}.Build()
	File_utils_proto = out.File
	file_utils_proto_rawDesc = nil
	file_utils_proto_goTypes = nil
	file_utils_proto_depIdxs = nil
}
